from lista import CircularList

dl= CircularList()
print(f"dl Esta vacia? {dl.is_empty()}")
print("-----------Insert-------------")
print("se agregan los valores en el siguiente orden: \n24.6 , 24.5 , 25 , 25 , 24 , 7 ")
dl.insert(24.6)
dl.insert(24.5)
dl.insert(25)
dl.insert(25)
dl.insert(24)
dl.insert(7)
dl.transversal()
print("\n-----------Search-------------")
print(f"se busca el elemento 7 y el resutado es: {dl.search(7)}")
print(f"se busca el elemento 6541321 y el resutado es: {dl.search(6541321)}")
print(f"se busca el elemento 0 y el resutado es: {dl.search(0)}")
print("\n-----------Insert-------------")
print("se agregan los valores en el siguiente orden:\nun insert vacio, un 32 y un 0")
dl.insert()
dl.insert(32)
dl.insert(0)
dl.transversal()
print("\n-----------Remove-------------")
dl.remove()
dl.remove(32)
dl.remove(24.5)
dl.transversal()
print("FIN :c")
