from listas import LinkedList

l = LinkedList()
print(f"L esta vacia ? { l.is_empty() } ")
l.append(10)
l.append(5)
l.append(6)
l.append(20)
print(f"L esta vacia ? { l.is_empty() } ")
l.transversal()
l.remove(10)
l.transversal()
l.preppend(3)
l.transversal()
x=l.tail()
print(x.data)
print("----------se pide la posicion 2 de la lista l")
print("el numero en esa posicion es= " , l.get(2))
print("----------ahora se pide la posicion 1789 de la lista l")
print(l.get(1789))
print("-------despues del 3 se agrega un 0")
l.add_after(3,0)
l.transversal()
print("-------antes del 0 se agrega un 1")
l.add_before(0,1)
l.transversal()
